application: webglstarfield
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.application

- url: /starfield_min\.js
  static_files: starfield_min.js
  upload: starfield_min.js

- url: /bg\.png
  static_files: bg.png
  upload: bg.png

libraries:
- name: webapp2
  version: "2.5.2"